import openai
import random

# First, set up your OpenAI API credentials
openai.api_key = "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"

# Define a function to generate random paragraphs using the GPT-3.5 model
def generate_paragraph():
    prompt = "The following is an intelligent-sounding paragraph generated by an AI:\n\n"
    response = openai.Completion.create(
        engine="text-davinci-002",
        prompt=prompt,
        temperature=random.uniform(0.5, 1.0),
        max_tokens=random.randint(50, 200),
        n_best=1,
        stop=None
    )
    return response.choices[0].text

# Call the function to generate a random paragraph
print(generate_paragraph())

